server:
  port: 8008
spring:
  data:
    mongodb:
      uri: mongodb://localhost/spring-cloud
eureka:
  instance:
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false