eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  ignored-services: "*"
  prefix: /api
  routes:
    book-catelog-service:
      path: /catelog/**
      url: http://localhost:8006
      strip-prefix: false
    book-order-service:
      path: /order/**
      url: http://localhost:8008
      strip-prefix: false
    book-shopping-service:
      path: /cart/**
      url: http://localhost:8087
      strip-prefix: false
ribbon:
  eureka:
    enabled: false