eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    book-catelog-service:
      path: /catelog/**
      url: http://localhost:8006/catelog
ribbon:
  eureka:
    enabled: false