eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  prefix: /api
  routes:
    book-catelog-service:
      path: /catelog/**
      url: http://localhost:8006
      strip-prefix: false
ribbon:
  eureka:
    enabled: false